### PR TITLE
[14.0][ADD] currency_rate_update_nbp

### PR DESCRIPTION
**Pull request by florian-dacosta**
Synchronize rate from the National Bank of Poland.
It is actually kind of a migration from v9/v10.

Still WIP for now

PR moved from currency repo : https://github.com/OCA/currency/pull/126

### CODE REVIEW

**Comment by uro** [comment]
Hello @pedrobaeza, can we merge this one?

**Comment by pedrobaeza** [comment]
Well, there's a WIP mark that not sure if it's still applicable, but @OCA/local-poland-maintainers should be the main ones to merge this. Not sure if they are active though...

**Comment by florian-dacosta** [comment]
Well there are no tests for now and I don't really have time to work on this soon, but the module should work.
@uro Could you do some functional tests to approve this ?

If it get one approve, we could maybe merge this as an alpha module and improve it (add tests) later ?

**Comment by TadeuszKarpinski** [comment]
I added tests here: https://github.com/OCA/l10n-poland/pull/9

**Pull request closed without merging**
